import { contextBridge, ipcRenderer } from 'electron';
import type { ContentKind, DailyPushSettings, GroupMessageConfigInput, ItineraryItem, ItinerarySettings, NaturalLanguageCommand, WeatherJobSettings } from '../src/domain/business';

contextBridge.exposeInMainWorld('travelbot', {
  authStatus: () => ipcRenderer.invoke('auth-status'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSchedule: (settings: { enabled: boolean; channel?: 'bot' | 'groupmsg'; groupIds: string[]; groupNames: string[]; customerChatIds?: string[]; intervalMinutes: number; message: string }) => ipcRenderer.invoke('save-schedule', settings),
  listGroups: () => ipcRenderer.invoke('list-groups'),
  startAuth: () => ipcRenderer.invoke('auth-start'),
  sendTest: (content: string, groupIds: string[]) => ipcRenderer.invoke('send-test', content, groupIds),
  openImage: (path: string) => ipcRenderer.invoke('open-image', path),
  weatherPreview: (location: string) => ipcRenderer.invoke('weather-preview', location),
  contentSearch: (input: { query: string; kind?: ContentKind }) => ipcRenderer.invoke('content-search', input),
  contentCommand: (text: string) => ipcRenderer.invoke('content-command', text),
  contentConfirm: (input: { command: NaturalLanguageCommand; confirmed: boolean }) => ipcRenderer.invoke('content-confirm', input),
  getWeatherJob: () => ipcRenderer.invoke('get-weather-job'),
  saveWeatherJob: (input: Omit<WeatherJobSettings, 'id' | 'lastSentAt' | 'lastResult'>) => ipcRenderer.invoke('save-weather-job', input),
  runWeatherJob: () => ipcRenderer.invoke('run-weather-job'),
  groupMessageConfig: () => ipcRenderer.invoke('groupmsg-get-config'),
  saveGroupMessageConfig: (input: GroupMessageConfigInput) => ipcRenderer.invoke('groupmsg-save-config', input),
  listCustomerGroups: () => ipcRenderer.invoke('groupmsg-list-groups'),
  sendGroupMessage: (input: { chatIds: string[]; content: string }) => ipcRenderer.invoke('groupmsg-send', input),
  groupMessageHistory: () => ipcRenderer.invoke('groupmsg-history'),
  groupMessageResult: (msgid: string) => ipcRenderer.invoke('groupmsg-result', msgid),
  dailyPush: () => ipcRenderer.invoke('daily-get'),
  saveDailyPush: (input: DailyPushSettings) => ipcRenderer.invoke('daily-save', input),
  dailyPushGroups: (ownerUserIds: string[]) => ipcRenderer.invoke('daily-list-groups', ownerUserIds),
  previewDailyPush: (input?: DailyPushSettings) => ipcRenderer.invoke('daily-preview', input),
  runDailyPush: () => ipcRenderer.invoke('daily-run'),
  itinerary: () => ipcRenderer.invoke('itinerary-get'),
  saveItinerarySettings: (input: ItinerarySettings) => ipcRenderer.invoke('itinerary-save-settings', input),
  loadItineraryGroups: (ownerUserIds: string[]) => ipcRenderer.invoke('itinerary-load-groups', ownerUserIds),
  parseItinerary: (text: string) => ipcRenderer.invoke('itinerary-parse', text),
  importItinerary: (input: { text: string; mode: 'append' | 'replace' }) => ipcRenderer.invoke('itinerary-import', input),
  updateItineraryItem: (input: { id: string; patch: Partial<Pick<ItineraryItem, 'separate'>> }) => ipcRenderer.invoke('itinerary-update-item', input),
  deleteItineraryItems: (input: { ids?: string[]; groupName?: string; beforeToday?: boolean }) => ipcRenderer.invoke('itinerary-delete-items', input),
  previewItineraryJob: (jobId: string) => ipcRenderer.invoke('itinerary-preview-job', jobId),
  runItineraryJob: (jobId: string) => ipcRenderer.invoke('itinerary-run-job', jobId),
  checkItineraryConfirmations: () => ipcRenderer.invoke('itinerary-check-confirmations'),
});
