/// <reference types="vite/client" />
import type { ContentKind, NaturalLanguageCommand, WeatherGreeting, WeatherJobSettings } from './domain/business';
declare global {
  interface Window { travelbot: { authStatus(): Promise<CliResult>; listGroups(): Promise<{ ok: boolean; groups: Array<{ id?: string; name: string; lastTime?: string }>; stderr?: string }>; getSettings(): Promise<ScheduleSettings>; saveSchedule(settings: ScheduleInput): Promise<{ ok: boolean; stderr?: string; settings?: ScheduleSettings }>; startAuth(): Promise<CliResult & { pending?: boolean; qrcode?: string | null }>; sendTest(content: string, groupIds: string[]): Promise<CliResult>; openImage(path: string): Promise<boolean>; weatherPreview(location: string): Promise<{ ok: boolean; stderr?: string; greeting?: WeatherGreeting }>; contentSearch(input: { query: string; kind?: ContentKind }): Promise<{ ok: boolean; stderr?: string; items: unknown[] }>; contentCommand(text: string): Promise<{ ok: boolean; stderr?: string; command?: NaturalLanguageCommand; items?: unknown[]; requiresConfirmation?: boolean }>; contentConfirm(input: { command: NaturalLanguageCommand; confirmed: boolean }): Promise<{ ok: boolean; stderr?: string; item?: unknown }>; getWeatherJob(): Promise<WeatherJobSettings>; saveWeatherJob(input: Omit<WeatherJobSettings, 'id' | 'lastSentAt' | 'lastResult'>): Promise<{ ok: boolean; stderr?: string; job?: WeatherJobSettings }>; runWeatherJob(): Promise<{ ok: boolean; stderr?: string; greeting?: WeatherGreeting }>; }; }
  interface ScheduleInput { enabled: boolean; groupIds: string[]; groupNames: string[]; intervalMinutes: number; message: string; }
  interface ScheduleSettings extends ScheduleInput { chatIds: string[]; lastRun?: string; lastResult?: string; }
  interface CliResult { ok: boolean; stdout?: string; stderr?: string; step?: string; pending?: boolean; }
}
export {};
