/// <reference types="vite/client" />
import type { ContentItem, ContentKind, CustomerGroup, DailyPushSettings, DailyPushView, GroupMessageConfigInput, GroupMessageConfigView, GroupMessageRecord, GroupMessageResult, NaturalLanguageCommand, WeatherGreeting, WeatherJobSettings } from './domain/business';
declare global {
  interface Window { travelbot: { authStatus(): Promise<CliResult>; listGroups(): Promise<{ ok: boolean; groups: Array<{ id?: string; name: string; lastTime?: string }>; stderr?: string }>; getSettings(): Promise<ScheduleSettings>; saveSchedule(settings: ScheduleInput): Promise<{ ok: boolean; stderr?: string; settings?: ScheduleSettings }>; startAuth(): Promise<CliResult & { pending?: boolean; qrcode?: string | null }>; sendTest(content: string, groupIds: string[]): Promise<CliResult>; openImage(path: string): Promise<boolean>; weatherPreview(location: string): Promise<{ ok: boolean; stderr?: string; greeting?: WeatherGreeting }>; contentSearch(input: { query: string; kind?: ContentKind }): Promise<{ ok: boolean; stderr?: string; items: ContentItem[] }>; contentCommand(text: string): Promise<{ ok: boolean; stderr?: string; command?: NaturalLanguageCommand; items?: unknown[]; requiresConfirmation?: boolean }>; contentConfirm(input: { command: NaturalLanguageCommand; confirmed: boolean }): Promise<{ ok: boolean; stderr?: string; item?: unknown }>; getWeatherJob(): Promise<WeatherJobSettings>; saveWeatherJob(input: Omit<WeatherJobSettings, 'id' | 'lastSentAt' | 'lastResult'>): Promise<{ ok: boolean; stderr?: string; job?: WeatherJobSettings }>; runWeatherJob(): Promise<{ ok: boolean; stderr?: string; greeting?: WeatherGreeting }>; groupMessageConfig(): Promise<GroupMessageConfigView>; saveGroupMessageConfig(input: GroupMessageConfigInput): Promise<{ ok: boolean; stderr?: string; config?: GroupMessageConfigView }>; listCustomerGroups(): Promise<{ ok: boolean; stderr?: string; groups: CustomerGroup[] }>; sendGroupMessage(input: { chatIds: string[]; content: string }): Promise<{ ok: boolean; stderr?: string; record?: GroupMessageRecord; failList?: string[] }>; groupMessageHistory(): Promise<GroupMessageRecord[]>; groupMessageResult(msgid: string): Promise<{ ok: boolean; stderr?: string; result?: GroupMessageResult }>; dailyPush(): Promise<DailyPushView>; saveDailyPush(input: DailyPushSettings): Promise<{ ok: boolean; stderr?: string; view?: DailyPushView }>; dailyPushGroups(ownerUserIds: string[]): Promise<{ ok: boolean; stderr?: string; groups: CustomerGroup[] }>; previewDailyPush(input?: DailyPushSettings): Promise<{ ok: boolean; stderr?: string; content?: string }>; runDailyPush(): Promise<{ ok: boolean; message: string; content?: string; errors: string[]; view?: DailyPushView }>; }; }
  interface ScheduleInput { enabled: boolean; channel?: 'bot' | 'groupmsg'; groupIds: string[]; groupNames: string[]; customerChatIds?: string[]; intervalMinutes: number; message: string; }
  interface ScheduleSettings extends ScheduleInput { channel: 'bot' | 'groupmsg'; chatIds: string[]; customerChatIds: string[]; lastRun?: string; lastResult?: string; }
  interface CliResult { ok: boolean; stdout?: string; stderr?: string; step?: string; pending?: boolean; }
}
export {};
